### PR TITLE
Install Visual Term Description Editor

### LINKED ISSUE #188: Taxonomy descriptions do not have Rich Text editing
From Lex:

>  Staff pages are showing bios condensed into one big paragraph? (For context – some people used to have multiple short grafs to break up their bio information, but it seems to be all into one big graf). Is this something we have to go in and manually fix? For example: Dan’s page looks insane: https://theworld.org/contributors/dan-lothian

### PR DESCRIPTION
**Pull request by brandonhundt**
Closes #188 

- Adds rich text editor to term page descriptions

## To Review

- [ ] Checkout Branch.
- [ ] Run `npm run local` (or `npm run refresh` if you want a fresh database.)
- [ ] Go to http://the-world-wp.lndo.site/.
- [ ] Run `wordpress` branch of frontend and ensure faust settings are pointing to local dev

> ...then...

- [ ] Go to a contributor
- [ ] Note the full editor is available to the editor
- [ ] make a change and update
- [ ] Confirm change in frontend

## Questions:
- We might want to patch this to exclude certain markup

### CODE REVIEW

**Comment by brandonhundt** [comment]
@rpeterman-gp Ready if you want to take a look. I didn't do anything other than try this plugin. If you don't think it's a good fit, we can scrap.

**Comment by rpeterman-gp** [comment]
Adding rich text to term descriptions is fine, but I think we need a separate Bio field for contributors. The description is used in SOE meta tags, and shouldn't be super long. I added the Bio field. Contributors should always set a paragraph length description, and add a bio value if they want anything longer than a paragraph.

**Comment by rpeterman-gp** [comment]
With the Bio field in place, it is not a requirement to have the rich text editor on the term description field, though it may be useful.

**Review by rpeterman-gp — APPROVED** [review]
Looks good. Go ahead and merge if you want to keep the rich text editor on the term description fields.

**Pull request merged**
