### PR TITLE
#229 wp-mail-smtp install

### LINKED ISSUE #229: PW reset emails not sending
We need to set up SMTP, which may require installing a plugin. 

Likely we can go into the Drupal site to pull out previous mail credentials.

### PR DESCRIPTION
**Pull request by brandonhundt**
Closes #229

- Installs WP Mail SMTP plugin recommended by Pantheon

## NOTE:
- I got it working locally and confirmed it sent me an email, but we will need to configure this on live, so we should deploy this to live and configure there. 

## To Review

- [x] Checkout Branch.
- [x] Run `npm run local` (or `npm run refresh` if you want a fresh database.)
- [ ] Go to http://the-world-wp.lndo.site/wp-admin.

> ...then...

- [x] Confirm the plugin is installed (It might give you a SMTP wizard as soon as you log in.)

If you must test locally:

- [x] If the Wizard is open, select Other SMTP. (I don't want to pay to do this through the Amazon API, which would require the pro module.)
- [x] Go into 1pass and look up `theworld.org SES SMTP` for creds
- [x] Enter the Creds
- [x] email is `editors@theworld.org`
- [x] Send a test email
- [ ] Go to the Users list, select another account set to an email address you have access to, send a password reset link
- [ ] Confirm its in your inbox. 
- [x] OR logout and attempt a password reset. Ensure reset link is in inbox.

### CODE REVIEW

**Comment by gtenaschuk** [comment]
@brandonhundt or @rpeterman-gp if possible we can use this PR and add the `[deploy:staging]` to test if the automatic deploy to staging environment works properly. Then, you will need to do the deploy from test to live manually but it will help to test if the automatic process stops in the correct env.

**Comment by rpeterman-gp** [comment]
@gtenaschuk Wouldn't the string to add be `[deploy:test]`? I didn't see any condition in the workflows to handle an environment called `staging`.

**Comment by gtenaschuk** [comment]
You Are right @rpeterman-gp !! the correct is [deploy:test] sorry, not sure why i confused it with staging if it is clear here https://github.com/PRX/cms.theworld.org/issues/227 🫤

**Review by rpeterman-gp — APPROVED** [review]
Worked for me locally. I also added a quick update to our PR template to update the setup instructions to match changes we have made to our scripts.

**Comment by brandonhundt** [comment]
@gtenaschuk Deploy to Test worked as expected! Thanks.

**Pull request merged**
