### PR TITLE
WIP: Remove ACF migration blocks

### PR DESCRIPTION
**Pull request by gtenaschuk**
- Remove ACF Groups for Migration fields not being used anymore.

### CODE REVIEW

**Comment by rpeterman-gp** [comment]
Is removing the files supposed to remove the field groups from the admin? I am still seeing them even after a sync. Do we have to manually remove them via the admin as well?

**Comment by gtenaschuk** [comment]
Hey @rpeterman-gp sorry for my late reply here.
Yes, i forgot to mention that i would wait for the deploy to delete them in the database.
When you have a group in the database  but does not have a JSON file stored in the filesystem you will see the groups with the status "Awainting save". Like in the image attached, that happens because i removed the field from the git repo.
Captura de pantalla 2024-05-03 a la(s) 12 06 02

**Comment by rpeterman-gp** [comment]
@gtenaschuk Will removing the fields from the database also remove the meta data records for them? We still rely on some of these fields, such as the media `original_uri` meta data.

**Comment by gtenaschuk** [comment]
Hey @rpeterman-gp no, they are not going to delete the meta data.
For that we will run these queries when the code is in live and no more fields will be available to store data in the database.
https://docs.google.com/document/d/1_xJZBj9iSNsS7VcukuJS5gOUph_AboVPUk5NXABNpbM/edit

**Comment by gtenaschuk** [comment]
We are going to work on other post types next week, because Episodes need more attention since we are using migrated fields in other groups using the same meta key and we need to keep them in the db.

**Review by rpeterman-gp — APPROVED** [review]
Lets's go! :shipit:

**Pull request merged**
