### PR TITLE
Minor update to test automatic deploy

### PR DESCRIPTION
**Pull request by gtenaschuk**

### CODE REVIEW

**Review by brandonhundt — APPROVED** [review]
:) good luck @gtenaschuk

**Comment by gtenaschuk** [comment]
Woohoo! :P

**Comment by gtenaschuk** [comment]
@brandonhundt i created this new issue to test the others deploy options, i hope it is ok if i create GH issues, or you can delete it and recreate it please :)
https://github.com/PRX/cms.theworld.org/issues/227

**Comment by brandonhundt** [comment]
Go for it! @gtenaschuk

**Pull request merged**
