### PR TITLE
Sync WP-CFM bundles with live db settings

### PR DESCRIPTION
**Pull request by brandonhundt**
- Syncs wp-cfm bundles from the latest live db backup 
- I've confirmed the wp-cpm directories are writable in Pantheon
- 🤞 

## To Review

- [ ] Checkout Branch.
- [ ] Run `npm run local` (or `npm run refresh` if you want a fresh database.)
- [ ] Go to http://the-world-wp.lndo.site/.

> ...then...

- [ ] go to WP-CFM setting page http://the-world-wp.lndo.site/wp-admin/options-general.php?page=wpcfm
- [ ] Under Dev `pull` all bundles
- [ ] Change to Live `pull` all bundles
- [ ] Ensure diffs are clean
- [ ] Poke around settings (like permalinks and Taxopress) and ensure settings are as we want them.

### CODE REVIEW

**Review by rpeterman-gp — APPROVED** [review]
Approving in hopes it works in the live env. I couldn't get it to pull changes into my lando db. 🤷 :shipit:

**Comment by gtenaschuk** [comment]
Hey Brandon, i didn't use wp-cfm too much but i think that Rick cant sync the settings because the folder i saw in the wp-cfm code is /private/config/[dev,live] and in the commits i saw /wp-content/config/dev

**Comment by rpeterman-gp** [comment]
@gtenaschuk We have a wp-cfm-path plugin that was written by 4K that is setting the CFM files directory to `/wp-content/config/[dev,live]`. Do we need this plugin if we should be using the wp-cfm plugin's default path?

**Comment by gtenaschuk** [comment]
Hey @rpeterman-gp I didn't see that, I made that comment because when I accessed to the WP-CFM settings it was asking to make the `/private/config/[dev,live]` folders writable.

**Comment by gtenaschuk** [comment]
We can do the same in that case, making `/wp-content/config/[dev|live]` writable as we did with the ones in `/private`

**Comment by brandonhundt** [comment]
closing this. won't fix

**Pull request closed without merging**
