### PR TITLE
Update plugins 21 August, 2024.

### PR DESCRIPTION
**Pull request by Sean12mps**
## Plugin Updates
```
----------------------------
Advanced Custom Fields PRO
Version 6.3.3

Pantheon Advanced Page Cache	
Version 2.0.0

Redirection	
Version 5.4.2

TaxoPress Pro	
Version 3.21.1

WPGraphQL	
Version 1.27.2

Yoast SEO	
Version 23.0
============================
```

## To Review
@brandonhundt 
There's a notice from GraphQL plugin for this update.
```
This release contains an internal refactor for how the Type Registry is generated which should lead to significant performance improvements for most users. While there are no intentional breaking changes, because this change impacts every user we highly recommend testing this release thoroughly on staging servers to ensure the changes don't negatively impact your projects.
```
Might be good to run some tests from the frontend side to check if everything is still up and running as it should.

### CODE REVIEW

**Comment by brandonhundt** [comment]
Going to let @rpeterman-gp test the frontend with this one.

**Review by rpeterman-gp — APPROVED** [review]
GraphQL API works as expected after update. :shipit:

**Comment by Sean12mps** [comment]
Thanks @brandonhundt @rpeterman-gp !

**Comment by Sean12mps** [comment]
Merging upstream in Pantheon.

**Pull request merged**
