### PR TITLE
WPCFM

### PR DESCRIPTION
**Pull request by joetower**
### Details
- Adds a dev workflow with `npm run` and `lando`
- Adds two ways to manage configuration or environment settings
    - WP-CFM plugin. This plugin is controlled via the Admin UI and allows you to create environment specific bundles. These are manually imported/exported.
    - MU Plugin - dev-specific-configs.php and live-specific-configs.php files. These allow a developer to manually add config changes that are automatically run once the site is deployed.

### Testing
- [x] Grab a database export from pantheon and place it in the `reference/` directory
- [x] Run `nvm use` then `npm install` then `lando start`
- [x] Run `npm run refresh`
- [x] Copy the random password the refresh script outputs and use it to log into Wordpress with `local-admin` being your user account.
- [x] Go to http://the-world-wp.lndo.site/wp-admin/options-general.php?page=wpcfm and switch between the environments (dev / live specifically) - Verify when switching to the live environment you now see a new config option ontop of all the other dev/test config options. Switching back to dev or test should hide this live config option.
- [x] Note the one bundle currently in place: `active plugins`
- [x] Create another bundle and confirm that if you `push` the bundle the bundle gets created as a file in `wp-content/config/[environment]`

### Notes
- There are only two environment prepped in this PR 
    - `dev` = local, pantheon multidev, and pantheon dev environments
    - 'live` = pantheon test and live environments
- WP-CFM exports/imports are manual. This means that when code is deployed to a specific environment the release manager will need to manually `Pull` the appropriate bundle. This can also be done via terminus. `terminus wp the-world-wp.[environment] config pull [bundle_name]`

### CODE REVIEW

**Comment by callinmullaney** [comment]
@brandonhundt I think I got this PR in a place that is reviewable. I added some notes that give an override of the PRs limitations and environment definitions.

**Review by brandonhundt — COMMENTED** [review]
@callinmullaney I'm running into an issue...

1. I run `nvm use` and `Now using node v16.13.1 (npm v8.1.2)`
2. `npm install` runs fine
3. `lando start` fails with `ERROR ==> node version 16 is not supported message=node version 16 is not supported, stack=Error: node version 16 is not supported`

Which is a little weird. I've also tried changing the nvm package to 14, but it looks to be locked on 16. 

Maybe lando is expecting 14 instead of 16?

Thanks!

**Comment by brandonhundt** [comment]
This is working after I updated lando to `3.6.0`!

**Comment by callinmullaney** [comment]
@brandonhundt Updated the readme with specifics around lando and node versions :+1:

**Comment by rpeterman-gp** [comment]
Should we add `reference/` directory to the .gitignore?

**Review by brandonhundt — APPROVED** [review]
Thanks @callinmullaney for finishing this off! Works as expected.

I also added the reference directory to the gitignore file. :shipit:

**Pull request merged**
