### PR TITLE
Update plugins 17 September, 2024.

### PR DESCRIPTION
**Pull request by Sean12mps**
Plugin updates
```
advanced-custom-fi | 6.3.5  => 6.3.6
faustwp            | 1.3.2  => 1.4.1
taxopress-pro      | 3.23.0 => 3.25.1
wp-graphql         | 1.28.0 => 1.28.1
wordpress-seo      | 23.3   => 23.4
```

### CODE REVIEW

**Comment by gtenaschuk** [comment]
@rpeterman-gp or @brandonhundt can you review this? i can use this PR to test the automatic deploy production feature with it :)

**Review by rpeterman-gp — APPROVED** [review]
Mostly patches. Faust minor version only adds a new setting that shouldn't affect the features we use. :shipit:

**Comment by brandonhundt** [comment]
@gtenaschuk go for it!

**Comment by gtenaschuk** [comment]
Thanks!
I have made the merge with `[deploy:live]` and the merge was pushed to dev -> test -> live environments automatically.
I added more info here https://github.com/PRX/cms.theworld.org/issues/227

**Pull request merged**
