### PR TITLE
Cleanup Post Tags

### PR DESCRIPTION
**Pull request by gtenaschuk**
- Loop Post Tags searching duplicated slugs in Custom Taxonomies
- Associate Posts and Episodes to Custom taxonomies found as duplicated elements with Post Tags
- Remove the Association between duplicated Post Tags and Posts and Episodes

IMPORTANT: If the Post Tag is repeated in more than 1 custom taxonomy, for example Countries, Categories and Social Tags, the Posts and Episodes will be associated to the 3 of them.

### CODE REVIEW

**Comment by rpeterman-gp** [comment]
@gtenaschuk I see that functions were aded to the helper class, but don't see any changes that queue those up to be run. How would this process be started and monitored?

**Comment by gtenaschuk** [comment]
@rpeterman-gp Those methods can be run by wp-cli, we were trying to create all the things we can prepared to run with wp-cli because it is much faster than running things from the UI.
So to get the number of duplicated tags the process to run is `terminus wp the-world.issue-122 tw-fix get_duplicated_post_tags_number` and the process to cleanup post tags is `terminus wp the-world.issue-122 tw-fix 
 post_tags_fix_duplicate ` and we have different logs to display parts of the process in the terminal.

**Comment by gtenaschuk** [comment]
Of course, will add that to the docs and will let you know.

**Comment by gtenaschuk** [comment]
Documentation added

**Review by rpeterman-gp — APPROVED** [review]
Thank you for the docs! Ran it on my local env and looks to do the job on the stories it affected. :shipit:

**Pull request merged**
